version: "3.4"

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: swapi-api
        env_file:
            - .env
        ports:
            - "9000:9000"
        depends_on:
            - db

    db:
        image: "postgres"
        container_name: postgresprisma
        ports:
            - "2345:5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_DB: "swapidb"
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
    postgres:
        name: swapidb
